### PR TITLE
fix(da-impl): restore the test suite

### PR DESCRIPTION
**Pull request by SeeWhatsOn**
The `packages/da-impl` cucumber suite has not run since **April**. `npm run test` is wired into CI at `.github/workflows/ci.yml:43`, so the **Test job has been red on `main` for months** — unnoticed because Semgrep, CodeQL and Scorecard pass independently.

It turned out to be four separate faults stacked on top of each other, each hidden behind the one before it. This PR fixes all four. The suite now runs.

| | Before | After |
|---|---|---|
| Scenarios executed | **0** | **90** |
| Passing | 0 | **88** |
| Failing | — | 2 (see below) |
| Process exit | **hangs forever** | **exits, 29s** |

Each fault is a separate commit, reviewable on its own.

---

## 1. `@finos/fdc3-testing` was unresolvable — `a8124a9`

```
test/step-definitions/app-channel.steps.ts(4,31): error TS2307:
Cannot find module '@finos/fdc3-testing'
```

**7e9a1da** ("Remote app support", #211) added it as a local path — `"../../../FDC3/packages/fdc3-testing"` — pointing at a sibling checkout of the FINOS/FDC3 monorepo. **3076455** ("Sail security demo", #234) removed that line but only reformatted the imports, leaving 8 files referencing a module that no longer resolved.

The dependency cannot be restored. The real package is `@finos/testing` in `finos/FDC3`, marked **`"private": true`** and deliberately never published — `npm view` 404s on both names. And the step definitions are not dead code: `cucumber.yml` has `tags: "not @failing"`, but there are **zero `@failing` tags in any `.feature` file**, so nothing is being skipped.

Instead this ports the local stand-in that already exists on the v3 branch lineage at **f44dcbd**, where the same problem was solved independently:

- **add** `test/support/matching.ts` — `handleResolve`, `doesRowMatch`, `matchData`
- **add** `test/support/setupGenericSteps.ts` — the generic steps and the ajv-based `Given schemas loaded` step
- **repoint** the 8 step-definition files

No config change needed: `CustomWorld` already exposes the `props` shape, and `cucumber.yml` already requires `test/support/*.ts`.

Four dependencies these files need were resolving transitively or not at all:

| Package | Was | Now |
|---|---|---|
| `ajv` | resolved to **6.14.0** — has no `dist/2019` | `^8.18.0` |
| `ajv-formats` | **absent from the lockfile entirely** | `^3.0.1` |
| `@finos/fdc3-schema` | transitive only | declared |
| `@finos/fdc3-context` | transitive only | declared |

## 2. `@finos/fdc3-standard@2.2.1-beta.3` is unloadable on Node 22+ — `c5c1e04`

```
ERR_MODULE_NOT_FOUND
.../@finos/fdc3-standard/dist/src/index.js imports './api/AppIntent'
```

Its `dist/src/index.js` uses ESM syntax with **extensionless relative imports** and the package sets no `"type": "module"`, so Node's ESM syntax auto-detection treats it as a module and then cannot resolve the paths. **CI runs Node 24**, so this affects CI as well as local runs.

`2.2.3` is packaged correctly (`"type": "module"`, `.js` extensions throughout). Bumps `@finos/fdc3`, `@finos/fdc3-context` and `@finos/fdc3-schema` together across `common`, `da-impl` and `web` so the resolved `@finos/fdc3-standard` is 2.2.3 everywhere.

## 3. `CustomWorld` imported a symbol that has never existed — `4a8c417`

`test/world/index.ts` imported `TestFDC3ServerFactory` from `test/support/TestFDC3ServerInstance`, which exports the class `TestFDC3ServerInstance` and the factory function `createTestFDC3ServerInstance` — never a symbol by that name, on this branch or on `main`.

Worth knowing why this stayed invisible: **`tsc` never type-checks the tests.** `packages/da-impl/tsconfig.json` sets `"exclude": ["test/**"]`. ts-node reports it at cucumber load time instead, which is why it only surfaced once the suite got far enough to load the World.

Switches to `createTestFDC3ServerInstance`, whose signature already matches the call site exactly — mirroring what f44dcbd does.

## 4. The process never exited — `2cb7cdf`

Cucumber wrote its reports and then hung until killed. In CI that means the job burns to its timeout rather than reporting a result.

Instrumenting `setTimeout`/`setInterval` and dumping what was still pending after `AfterAll` gives a single culprit:

```
LEAKCOUNT 1
LEAK setInterval(10) at new HeartbeatHandler (src/handlers/HeartbeatHandler.ts:54:26)
```

`HeartbeatHandler` starts an interval in its constructor. `heartbeat.feature` has three scenarios that enable heartbeats but only two that call `I stop the heartbeat handler`, so one interval outlives the run and holds the event loop open. There were **no `After` hooks in the suite at all**, so nothing else cleaned up either.

Adds an `After` hook calling `sc.shutdown()`. `TestFDC3ServerInstance.shutdown` already stops every registered handler and `HeartbeatHandler.shutdown` clears the interval, so this covers future handlers rather than just the heartbeat case. Deliberately not cucumber's `forceExit`, which would hide the leak rather than close it.

---

## Verification

```
90 scenarios (2 failed, 88 passed)
1018 steps (2 failed, 5 skipped, 1011 passed)
0m22.201s
```

Exits with code 1, reflecting the 2 genuine failures. `npm run build --workspaces` passes across all three workspaces.

## The 2 remaining failures

```
Opening An App With Context    expect(received).toHaveLength(expected)  Expected 0, received 1
App Responds to heartbeats     expect(received).toBeTruthy()           Received: false
```

They reproduce consistently — not flaky. They **cannot be attributed to the changes here**, because the suite has not executed in this repository since April; they are pre-existing behaviour that simply became visible again. Left for a follow-up rather than papered over with a `@failing` tag, so they stay in view.

**This PR does not make the Test job green.** It makes it *run*, report in 29 seconds, and fail honestly on 2 of 90 scenarios instead of failing to compile.

### CODE REVIEW

**Comment by robmoffat** [comment]
I think we should re-import da-impl from https://github.com/finos/FDC3/pull/1890, since it uses the new @finos/cucumber-testing-steps import.

**Comment by SeeWhatsOn** [comment]
> I think we should re-import da-impl from https://github.com/finos/FDC3/pull/1890, since it uses the new @finos/cucumber-testing-steps import.

Fixed! Migrated back to using your new testing lib. 
Would you review again please @robmoffat :+1:
